cursor --install-extension ajshortt.tokyo-hack
cursor --install-extension alefragnani.project-manager
cursor --install-extension bierner.color-info
cursor --install-extension christian-kohler.path-intellisense
cursor --install-extension davidanson.vscursor-markdownlint
cursor --install-extension dbaeumer.vscursor-eslint
cursor --install-extension donjayamanne.githistory
cursor --install-extension dwtexe.cursor-stats
cursor --install-extension eamodio.gitlens
cursor --install-extension enkia.tokyo-night
cursor --install-extension esbenp.prettier-vscursor
cursor --install-extension foxundermoon.shell-format
cursor --install-extension github.copilot
cursor --install-extension github.copilot-chat
cursor --install-extension github.vscursor-pull-request-github
cursor --install-extension golang.go
cursor --install-extension google.geminicursorassist
cursor --install-extension mattpocock.ts-error-translator
cursor --install-extension ms-vscursor-remote.remote-ssh
cursor --install-extension ms-vscursor-remote.remote-ssh-edit
cursor --install-extension ms-vscursor.makefile-tools
cursor --install-extension ms-vscursor.remote-explorer
cursor --install-extension panicbit.cargo
cursor --install-extension pfwobcke.vscursor-ttf
cursor --install-extension redhat.vscursor-yaml
cursor --install-extension rust-lang.rust-analyzer
cursor --install-extension serayuzgur.crates
cursor --install-extension tamasfe.even-better-toml
cursor --install-extension tyriar.sort-lines
cursor --install-extension visualstudioexptteam.intellicursor-api-usage-examples
cursor --install-extension visualstudioexptteam.vscursorintellicursor
cursor --install-extension wayou.vscursor-todo-highlight
cursor --install-extension zhuangtongfa.material-theme
