windsurf --install-extension ajshortt.tokyo-hack
windsurf --install-extension alefragnani.project-manager
windsurf --install-extension catppuccin.catppuccin-vsc
windsurf --install-extension davidanson.vswindsurf-markdownlint
windsurf --install-extension dbaeumer.vswindsurf-eslint
windsurf --install-extension donjayamanne.githistory
windsurf --install-extension eamodio.gitlens
windsurf --install-extension editorconfig.editorconfig
windsurf --install-extension emmanuelbeziat.vswindsurf-great-icons
windsurf --install-extension esbenp.prettier-vswindsurf
windsurf --install-extension foxundermoon.shell-format
windsurf --install-extension github.vswindsurf-pull-request-github
windsurf --install-extension golang.go
windsurf --install-extension google.geminiwindsurfassist
windsurf --install-extension mattpocock.ts-error-translator
windsurf --install-extension mkhl.shfmt
windsurf --install-extension ms-vswindsurf.makefile-tools
windsurf --install-extension naumovs.color-highlight
windsurf --install-extension njzy.stats-bar
windsurf --install-extension panicbit.cargo
windsurf --install-extension redhat.vswindsurf-yaml
windsurf --install-extension rooveterinaryinc.roo-cline
windsurf --install-extension rust-lang.rust-analyzer
windsurf --install-extension saoudrizwan.claude-dev
windsurf --install-extension serayuzgur.crates
windsurf --install-extension shan.windsurf-settings-sync
windsurf --install-extension sumneko.lua
windsurf --install-extension tamasfe.even-better-toml
windsurf --install-extension tyriar.sort-lines
windsurf --install-extension vswindsurf-icons-team.vswindsurf-icons
windsurf --install-extension wayou.vswindsurf-todo-highlight
windsurf --install-extension zhuangtongfa.material-theme
